### PR TITLE
Edits after submission

### PR DESCRIPTION
**Pull request by sarathms**
This addresses some of the concerns related to #22. The idea is to allow users to continue to make changes even after they have submitted some changes.

### CODE REVIEW

**Comment by sarathms** [comment]
Initial (`state: CLEAN`)
image

Editing (`state: IN_PROGRESS`)
image

Submitted (`state: PR_OPEN`)
image

**Comment by sarathms** [comment]
@agrabeli Can you please suggest better copy for the hints below the main submit button in the 3 different states shown in the previous comment?

**Comment by hellais** [comment]
I am taking a look at the latest changes, here is some feedback:
1. The section with the changes made should be hidden until some changes are proposed
2. When I add a new URL entry, the section on top doesn't update immediately, but it only updates after a while. It should update as soon as a URL is added.
3. The text "When you are done making changes, click Submit to propose your changes." should go above the submit button
4. We should drop the grey background around the submit button and just make it white


I don't know if you want to do it as part of this PR already, but we should also drop the nickname field from the login form and add the logout button.

**Comment by sarathms** [comment]
> I don't know if you want to do it as part of this PR already, but we should also drop the nickname field from the login form and add the logout button.

This was already done in #37 (https://github.com/ooni/test-lists-ui/pull/37/commits/a0a75e77255855167391175a331c1d0e56fc9f1f)

**Comment by hellais** [comment]
> I don't know if you want to do it as part of this PR already, but we should also drop the nickname field from the login form and add the logout button.

In #37 I only see the logout feature added, but not the dropping of the nickname field from the login form or am I missing something?

Can we make the preview deployment be aligned also with the merged PRs so we can test everything together?

**Comment by hellais** [comment]
I have done some light testing of this PR and it looks good to me.

This item:
> The section with the changes made should be hidden until some changes are proposed

has not been addressed, but I say we merge this and move forward with this as-is.

**Pull request merged**
